name: Build and Push Docker Image to GCR

on:
  push:
    branches:
    - master

env:
  WORKDIR: ./operator

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.WORKDIR }}
        file: ${{ env.WORKDIR }}/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
