name: E2E Tests

on:
  push:
  pull_request:


env:
  WORKDIR: ./operator

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-24.04
    steps:
    - name: Clone the code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ env.WORKDIR }}/go.mod

    - name: Install the latest version of kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Verify kind installation
      run: kind version

    - name: Create kind cluster
      run: kind create cluster

    - name: Running Test e2e
      working-directory: ${{ env.WORKDIR }}
      run: |
        go mod tidy
        make test-e2e
