name: Tests

on:
  push:
  pull_request:


env:
  WORKDIR: ./operator

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-24.04
    steps:
    - name: Clone the code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ env.WORKDIR }}/go.mod

    - name: Running Tests
      working-directory: ${{ env.WORKDIR }}
      run: |
        go mod tidy
        make test
